config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :comments
      resources :posts
      resources :projects

      root to: "users#index"
    end
  get 'errors/not_found'
  get 'errors/internal_server_error'

  devise_for :users

  get 'pages/home'
  root "pages#home"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :projects

  scope module: :blog, path: :blog do
    resources :posts
  end
end

app/views/shared/_alert.html.haml
.z-10.fixed.inset-0.flex.items-end.px-4.py-6.pointer-events-none.sm:p-6.sm:items-start{"aria-live" => "assertive"}
  .w-full.flex.flex-col.items-center.space-y-4.sm:items-end.transition.transition-all
    /
      Notification panel, dynamically insert this into the live region when it needs to be displayed

      Entering: "transform ease-out duration-300 transition"
      From: "translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
      To: "translate-y-0 opacity-100 sm:translate-x-0"
      Leaving: "transition ease-in duration-100"
      From: "opacity-100"
      To: "opacity-0"
    .max-w-sm.w-full.bg-white.shadow-lg.rounded-lg.pointer-events-auto.ring-1.ring-black.ring-opacity-5.overflow-hidden.border.border-2.shadow-md{class: "#{type == :error ? 'border-red-300' : 'bg-green-300'}"}
      .p-4
        .flex.items-start
          .flex-shrink-0
            / Heroicon name: outline/check-circle
            -# %svg.h-6.w-6.text-green-400{"aria-hidden" => "true", :fill => "none", :stroke => "currentColor", "stroke-width" => "2", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
            -#   %path{:d => "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
          .ml-3.w-0.flex-1{:class => "pt-0.5"}
            %p.text-sm.font-medium.text-gray-900= message
          .ml-4.flex-shrink-0.flex
            %button.bg-white.rounded-md.inline-flex.text-gray-400.hover:text-gray-500.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-indigo-500{:type => "button"}
              %span.sr-only Close
              / Heroicon name: solid/x
              %svg.h-5.w-5{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
                %path{"clip-rule" => "evenodd", :d => "M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z", "fill-rule" => "evenodd"}

app/views/shared/_card.html.haml
= link_to link, class: 'flex flex-col flex-1 transition hover:opacity-80' do
  .flex-shrink-0
    - if resource.image.attached?
      =image_tag(resource.image, class: 'w-full')
  .flex-1.bg-white.p-6.flex.flex-col.justify-between
    .flex-1
      %p.text-sm.font-medium.text-indigo-600
        %div.hover:underline Post
      %div.block.mt-2
        %p.text-xl.font-semibold.text-gray-900= resource.title
        %p.mt-3.text-base.text-gray-500= resource.excerpt
    .mt-6.flex.items-center
      .flex-shrink-0
        %div
          %span.sr-only= resource.author.name
          = image_tag resource.author.avatar, class: 'h-10 w-10 rounded-full'
      .ml-3
        %p.text-sm.font-medium.text-gray-900
          %div.hover:underline= resource.author.name
        .flex.space-x-1.text-sm.text-gray-500
          %time{:datetime => "2020-03-16"}= resource.created_at.to_date.to_formatted_s(:long)
          %span{"aria-hidden" => "true"} ·
          %span= pluralize(resource.reading_time, 'minute')

app/views/shared/_empty_section.html.haml
.text-center.col-span-full
  %svg.mx-auto.h-12.w-12.text-gray-400{"aria-hidden" => "true", :fill => "none", :stroke => "currentColor", :viewbox => "0 0 24 24"}
    %path{:d => "M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", "vector-effect" => "non-scaling-stroke"}
  %h3.mt-2.text-sm.font-medium.text-gray-900= message[:title]
  %p.mt-1.text-sm.text-gray-500= message[:body]
  .mt-6
  -if can? :create, resource
    = link_to link do
      %button.btn{type: "button"}
        / Heroicon name: solid/plus
        %svg.-ml-1.mr-2.h-5.w-5{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
          %path{"clip-rule" => "evenodd", :d => "M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z", "fill-rule" => "evenodd"}
        = message[:button]

app/views/shared/_footer.html.haml
%footer.bg-gray-800
  .max-w-7xl.mx-auto.py-12.px-4.overflow-hidden.sm:px-6.lg:px-8
    %nav.-mx-5.-my-2.flex.flex-wrap.justify-center{"aria-label" => "Footer"}
      .px-5.py-2
        %a.text-base.text-gray-500.hover:text-gray-900{:href => "#"} About
      .px-5.py-2
        %a.text-base.text-gray-500.hover:text-gray-900{:href => "#"} Blog
    .mt-8.flex.justify-center.space-x-6
      %a.text-gray-400.hover:text-gray-500{:href => "#"}
        %span.sr-only Facebook
        %svg.h-6.w-6{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 24 24"}
          %path{"clip-rule" => "evenodd", :d => "M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z", "fill-rule" => "evenodd"}
      %a.text-gray-400.hover:text-gray-500{:href => "#"}
        %span.sr-only Instagram
        %svg.h-6.w-6{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 24 24"}
          %path{"clip-rule" => "evenodd", :d => "M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z", "fill-rule" => "evenodd"}
      %a.text-gray-400.hover:text-gray-500{:href => "#"}
        %span.sr-only GitHub
        %svg.h-6.w-6{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 24 24"}
          %path{"clip-rule" => "evenodd", :d => "M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z", "fill-rule" => "evenodd"}
    %p.mt-8.text-center.text-base.text-gray-400 © 2022 Ivan Garcia, Inc. All rights reserved.

app/views/shared/_header.html.haml
%header.bg-red-700
  %nav.max-w-7xl.mx-auto.px-4.sm:px-6.lg:px-8{"aria-label" => "Top"}
    .w-full.py-4.flex.items-center.justify-between.border-b.border-black.lg:border-none
      .flex.items-center
        = link_to root_path do
          %span.sr-only Workflow
          = image_tag("logos/black-white.svg", alt: "logo", class: 'h-14 w-auto')
        .hidden.ml-10.space-x-8.lg:block
          = link_to 'Home', root_path, class: 'text-base font-medium text-white hover:text-indigo-50'
          = link_to 'Projects', projects_path, class: 'text-base font-medium text-white hover:text-indigo-50'
          = link_to 'Blog', posts_path, class: 'text-base font-medium text-white hover:text-indigo-50'
      - if user_signed_in?
        %div.flex.gap-3
          .ml-10.space-x-4
            = link_to 'Admin', admin_users_path, class: 'inline-block bg-gray-500 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-opacity-75'
          .space-x-4
            = button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'inline-block bg-gray-500 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-opacity-75'
      - else
        .ml-10.space-x-4
          = link_to 'Sign in', new_user_session_path, class: 'inline-block bg-gray-500 py-2 px-4 border border-transparent rounded-md text-base font-medium text-white hover:bg-opacity-75'
          = link_to 'Sign up', new_user_registration_path, class: 'inline-block bg-white py-2 px-4 border border-transparent rounded-md text-base font-medium text-red-700 hover:bg-indigo-50'
    .py-4.flex.flex-wrap.justify-center.space-x-6.lg:hidden
      = link_to 'Home', root_path, class: 'text-base font-medium text-white hover:text-indigo-50'
      = link_to 'Projects', projects_path, class: 'text-base font-medium text-white hover:text-indigo-50'
      = link_to 'Blog', posts_path, class: 'text-base font-medium text-white hover:text-indigo-50'

app/views/shared/_hero_section.html.haml
.pt-10.sm:pt-16.lg:pt-8.lg:overflow-hidden.bg-gradient-to-r.from-gray-700.to-gray-300.relative
  .mx-auto.max-w-7xl.lg:px-8
    .lg:grid.lg:grid-cols-2.lg:gap-8
      .mx-auto.max-w-md.px-4.sm:max-w-2xl.sm:px-6.sm:text-center.lg:px-0.lg:text-left.lg:flex.lg:items-center
        .lg:py-24.lg:h-full{class: 'h-[calc(100vh-170px)]'}
          %a.inline-flex.items-center.text-white.bg-black.rounded-full.p-1.pr-2.sm:text-base.lg:text-sm.xl:text-base.hover:text-gray-200{:href => "#"}
            %span.px-3.text-white.text-sm.font-semibold.leading-5.bg-red-700.rounded-full{:class => "py-0.5"} Need a website?
            %span.ml-4.text-sm Contact me
            / Heroicon name: solid/chevron-right
            %svg.ml-2.w-5.h-5.text-gray-500{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
              %path{"clip-rule" => "evenodd", :d => "M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z", "fill-rule" => "evenodd"}
          %h1.mt-4.text-4xl.tracking-tight.font-bold.text-white.sm:mt-5.sm:text-6xl.sm:tracking-tight.lg:mt-6.xl:text-6xl.xl:tracking-tight
            %span.block Ivan Garcia
            %span.block.text-red-700 Software Engineer
          %p.mt-3.text-base.text-white.sm:mt-5.sm:text-xl.lg:text-lg.xl:text-xl Over 3 years of experience developing websites for clients from around the world. Experienced in various technologies and languages.
      .mt-12.-mb-16.sm:-mb-48.lg:m-0.lg:relative
        .fadein.mx-auto.max-w-md.px-4.sm:max-w-2xl.sm:px-6.lg:max-w-none.lg:px-0
          = image_tag('ivan-removebg-preview.png', class: 'f1 w-full absolute lg:inset-y-0 lg:left-0 lg:h-full lg:w-auto lg:max-w-none')
          = image_tag('rugiet-ivan.png', class: 'f2 w-[80%] absolute lg:inset-y-0 lg:left-0 lg:h-full lg:w-auto lg:max-w-none')