config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :comments
      resources :posts
      resources :projects

      root to: "users#index"
    end
  get 'errors/not_found'
  get 'errors/internal_server_error'

  devise_for :users

  get 'pages/home'
  root "pages#home"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :projects

  scope module: :blog, path: :blog do
    resources :posts
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :bigint           not null, primary key
#  description :text
#  image       :string
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Project < ApplicationRecord
  has_one_attached :image
  has_rich_text :description
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    authorize_resource

    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource except: [:index, :show]

  def index
    @projects = Project.page(params[:page]).per(10)
  end


  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def edit; end

  def destroy
    @project.destroy

    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description, :image)
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/projects/_form.html.haml
= form_with model: @project, class: 'form' do |f|
  - if @project.errors.any?
    - @project.errors.full_messages.each do |message|
      = message
  .w-full
    = f.label :name, class: 'label'
    = f.text_field :name, class: 'input'
  .w-full
    = f.label :description, class: 'label'
    = f.rich_text_area :description, class: 'input'
  .w-full
    = f.label :image, class: 'label'
    = f.file_field :image, class: 'input'
  .w-full
    = f.submit 'Create Project', class: 'btn btn-primary'

app/views/projects/edit.html.haml
.max-w-3xl.mx-auto.px-4.sm:px-6.lg:max-w-4xl.lg:px-8.h-screen.mt-10
  %section
    .rounded-lg.bg-white.overflow-hidden.shadow.p-6
      %h1.text-center Edit Project

      = render 'form'

app/views/projects/index.html.haml
.bg-white
  .mx-auto.py-12.px-4.max-w-7xl.sm:px-6.lg:px-8.lg:py-24
    .space-y-12.lg:grid.lg:grid-cols-3.lg:gap-8.lg:space-y-0
      .space-y-5.sm:space-y-4
        %h2.text-3xl.font-bold.tracking-tight.sm:text-4xl About Us
        %p.text-xl.text-gray-500 Nulla quam felis, enim faucibus proin velit, ornare id pretium. Augue ultrices sed arcu condimentum vestibulum suspendisse. Volutpat eu faucibus vivamus eget bibendum cras.
      .lg:col-span-2
        - if @projects.empty?
          = render 'shared/empty_section', resource: Project, link: new_project_path, message: { title: 'No projects yet', body: 'Create a project to start', button: 'Create project' }
        - else
          %ul.space-y-12.sm:divide-y.sm:divide-gray-200.sm:space-y-0.sm:-mt-8.lg:gap-x-8.lg:space-y-0{:role => "list"}
          - @projects.each do |project|
            = link_to project_path(project.id) do
              %li.sm:py-8.list-none.hover:opacity-90.hover:bg-gray-100.rounded.p-3
                .space-y-4.sm:grid.sm:grid-cols-3.sm:items-start.sm:gap-6.sm:space-y-0
                  .aspect-w-3.aspect-h-2.sm:aspect-w-3.sm:aspect-h-4
                    = image_tag(project.image, class: 'object-cover shadow-lg rounded-lg')
                  .sm:col-span-2
                    .space-y-4
                      .text-lg.leading-6.font-medium.space-y-1
                        %h3= project.name
                        %p.text-indigo-600 Co-Founder / CEO
                      .text-lg
                        %p.text-gray-500= project.description
                      %ul.flex.space-x-5{:role => "list"}
                        %li
                          %a.text-gray-400.hover:text-gray-500{:href => "#"}
                            %span.sr-only Twitter
                            %svg.w-5.h-5{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20"}
                              %path{:d => "M6.29 18.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0020 3.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.073 4.073 0 01.8 7.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 010 16.407a11.616 11.616 0 006.29 1.84"}
                        %li
                          %a.text-gray-400.hover:text-gray-500{:href => "#"}
                            %span.sr-only LinkedIn
                            %svg.w-5.h-5{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20"}
                              %path{"clip-rule" => "evenodd", :d => "M16.338 16.338H13.67V12.16c0-.995-.017-2.277-1.387-2.277-1.39 0-1.601 1.086-1.601 2.207v4.248H8.014v-8.59h2.559v1.174h.037c.356-.675 1.227-1.387 2.526-1.387 2.703 0 3.203 1.778 3.203 4.092v4.711zM5.005 6.575a1.548 1.548 0 11-.003-3.096 1.548 1.548 0 01.003 3.096zm-1.337 9.763H6.34v-8.59H3.667v8.59zM17.668 1H2.328C1.595 1 1 1.581 1 2.298v15.403C1 18.418 1.595 19 2.328 19h15.34c.734 0 1.332-.582 1.332-1.299V2.298C19 1.581 18.402 1 17.668 1z", "fill-rule" => "evenodd"}


          -if can? :create, @project
            = link_to new_project_path do
              %button.btn.btn-primary{type: "button"}
                / Heroicon name: solid/plus
                %svg.-ml-1.mr-2.h-5.w-5{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
                  %path{"clip-rule" => "evenodd", :d => "M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z", "fill-rule" => "evenodd"}
                New Project

          = paginate @projects

app/views/projects/new.html.haml
%h1 New Project

= form_with model: @project do |f|
  - if @project.errors.any?
    - @project.errors.full_messages.each do |message|
      = message
  %div
    = f.label :name
    = f.text_field :name
  %div
    = f.label :description
    = f.rich_text_area :description
  %div
    = f.label :image
    = f.file_field :image
  %div
    = f.submit

app/views/projects/show.html.haml
%h1
  = @project.name

  %p
    = @project.description

  %div
    = image_tag(@project.image)